### ISSUE TITLE
Není pro verzi php (>=5.3.0)

### ISSUE THREAD

**Issue by mprof** [JZechy/Nette-AntiSpam#6]
Dobrý den,

vaše rozšíření potřebuje, přestože udáváte (PHP >=5.3.0) k bezchybnému autowiringu (PHP >=7.0.0) nebo dokonce 7.1, protože používáte "nullable types" v deklarované funkci. A to není úplně ok. Jinak je to dobrá myšlenka rozšíření, nějakou podobnou ochranu jsem už dlouho pro Nette hledal a chtěl jsem si sám napsat.

**File**: .../vendor/jzechy/nette-antispam/src/Validator.php
234:        /**
235:         * @param Session $session
236:         */
237:        public function setSession(Session $session)**: void** {
238:            $this->session = $session;
239:        }

**Comment by darkWolf-PR** [comment]
Taky sem na to bohužel právě přišel. Návratový typ void bohužel vyžaduje min. PHP 7.1 :-((

**Comment by JZechy** [comment]
Editor mám zafixovaný na >= PHP 7.1, tak mi při automatickém generování set/get nahodil i typy 😄 Odstraněni, zatagován nový release.
