### ISSUE TITLE
Povinná otázka

### ISSUE THREAD

**Issue by mprof** [JZechy/Nette-AntiSpam#7]
Tohle by chtělo dost velkej improve..

Třeba udělat setter na to, aby se dala otázka úplně vypnout (neloadovala se a nekontrolovala), protože v momentě, kdy se vypne javascript a funkci na validaci formu převezme prohlížeč, tak chce autofocusovat input konktrolní otázky (kterej mám schovanej CSSkem), protože ten se logicky nevyplní, jelikož to Vám řeší javascript, což úplně nevím jakej má smysl ve Vašem řešení, to už by to mohlo vyplnit rovnou PHPko. 

Nejlepší řešení podle mě je, aby se dalo injectnutí kontrolní otázky úplně odříznout, protože pokud se nepoužívá, tak to dělá jen neplechu a stejně pro roboty, kteří vyplňují své bloat texty stačí bohatě ten jeden hidden input třeba v kombinaci ještě toho checkboxu ... Upřímně bych řekl, že samotná kontrolní otázka v tomhle řešení nemá moc smysl, lepší je v kombinaci s tímhle použít reCaptchu nebo si rovnou do formu připsat vlastní kontrolní otázku, je to pak víc upravitelný, tohle by mělo dělat hlavně tu ochranu vůči spamu díky hidden inputu, protože to je hlavně to, co Nette\Application\UI\Form chybí.

Zatím jsem  tohle pořešil tak, že jsem editoval:

**QuestionGenerator.php**
```
/**
 * @return Html
 */
public function getQuestion() {
	$containerId = $this->getContainerId();
	$container = Html::el("div");
	$container->setAttribute("id", $containerId);

	$questionId = $this->getQuestionId();

	$this->labelPrototype->setAttribute("for", $questionId);
	$this->inputPrototype->setAttribute("id", $questionId);
	$this->inputPrototype->setAttribute("name", $this->getQuestionName());
	$this->inputPrototype->setRequired(false); // Není povinné

	$container->addHtml($this->labelPrototype);
	$container->addHtml($this->inputPrototype);

	$script = Html::el("script");
	$script->setHtml(
		"document.getElementById('$containerId').style.display = 'none';\n" .
		"document.getElementById('$questionId').value = " . $this->result . ";"
	);
	$container->addHtml($script);

	return $container;
}
```

**Validator.php**
```
/**
 * @return bool
 */
private function validateQuestion() {
	$value = $this->getData($this->questionInput);

	//return $value == $this->getSessionSection()->result;
	return true;
}
```

**Comment by mprof** [comment]
> Tohle by chtělo dost velkej improve..
> 
> Třeba udělat setter na to, aby se dala otázka úplně vypnout (neloadovala se a nekontrolovala), protože v momentě, kdy se vypne javascript a funkci na validaci formu převezme prohlížeč, tak chce autofocusovat input konktrolní otázky (kterej mám schovanej CSSkem), protože ten se logicky nevyplní, jelikož to Vám řeší javascript, což úplně nevím jakej má smysl ve Vašem řešení, to už by to mohlo vyplnit rovnou PHPko.
> 
> Nejlepší řešení podle mě je, aby se dalo injectnutí kontrolní otázky úplně odříznout, protože pokud se nepoužívá, tak to dělá jen neplechu a stejně pro roboty, kteří vyplňují své bloat texty stačí bohatě ten jeden hidden input třeba v kombinaci ještě toho checkboxu ... Upřímně bych řekl, že samotná kontrolní otázka v tomhle řešení nemá moc smysl, lepší je v kombinaci s tímhle použít reCaptchu nebo si rovnou do formu připsat vlastní kontrolní otázku, je to pak víc upravitelný, tohle by mělo dělat hlavně tu ochranu vůči spamu díky hidden inputu, protože to je hlavně to, co Nette\Application\UI\Form chybí.
> 
> Zatím jsem tohle pořešil tak, že jsem přidal:
> 
> ```
> 	/**
> 	 * @return Html
> 	 */
> 	public function getQuestion() {
> 		$containerId = $this->getContainerId();
> 		$container = Html::el("div");
> 		$container->setAttribute("id", $containerId);
> 		
> 		$questionId = $this->getQuestionId();
> 		
> 		$this->labelPrototype->setAttribute("for", $questionId);
> 		$this->inputPrototype->setAttribute("id", $questionId);
> 		$this->inputPrototype->setAttribute("name", $this->getQuestionName());
> 		$this->inputPrototype->setRequired(false); // Není povinné
> 		
> 		$container->addHtml($this->labelPrototype);
> 		$container->addHtml($this->inputPrototype);
> 		
> 		$script = Html::el("script");
> 		$script->setHtml(
> 			"document.getElementById('$containerId').style.display = 'none';\n" .
> 			"document.getElementById('$questionId').value = " . $this->result . ";"
> 		);
> 		$container->addHtml($script);
> 		
> 		return $container;
> 	}
> ```

**Comment by JZechy** [comment]
Ahoj,

smysl javascriptový otázky je jednoduchý: Předpokládá u primitivních spambotů nepoužití javascriptu, tudíž je pro něj nutno ji vyplnit. Pokud uživatel používá javascript, není touto otázkou zbytečně obtěžován - obstará to za něj javascript a schová ji mimo zraky. Pokud si JS vypne, pak si ji holt musí uživatel také vyplnit.

Cílem byla jistá neprůstřelnost řešení, tudíž proto jsem zkombinoval několik možností dohromady. Přesto IMHO by šel přidělat na setter na vypnutí.

**Comment by mprof** [comment]
Tohle chápu, ale jak jsem psal i když možná trošku hekticky, tak pokud má to pole "příznak" required, tak v případě schování chce základní html validace "focusovat" na pole, které je schované a to je špatně, protože to v konzoli bude házet chybu a celej form nepůjde odeslat. Nejlepší by opravdu bylo, aby se renderování a validace kontrolní otázky dala úplně vypnout, když se používá alternativní metoda jako třeba reCaptcha, která mi na tohle připadá beztak lepší. Samozřejmě se tu bavím o vypnutí JS celkově a to pak nepůjde ani reCaptcha. Každopádně já na tomhle rozšíření oceňuji hlavně řekněme ten "time control" před/po form akcích. Mimochodem úplně jsem neměl čas ten kód studovat a ani to testovat, ale jak máš vyřešený vypnutí cookies, když se SSID nepřenáší do url? Vrátí to prostě false a form se neodešle?

Ukázka validace: http://prntscr.com/l6m97q
